### PR TITLE
Dynamically size getcwd() buffer in get_dir function

### PR DESCRIPTION
**Pull request by n1tehawk**
This should fix issue #42.

### CODE REVIEW

**Comment by hishamhm** [comment]
I noticed you are no longer using getcwd_error. If I'm reading this patch correctly, if a system has NO_GETCWD defined and this is called after a previous function fails with ERANGE, this would loop allocating memory forever. Please check the NO_GETCWD defines at the top and handle that case too. Thanks!

**Comment by n1tehawk** [comment]
You're right, I missed that. I'm inclined to do away with the getcwd (re)definition via macro in that case, and handle the NO_GETCWD directly. Will take a look at it and amend the pull request...

**Comment by n1tehawk** [comment]
Btw: I wonder how that case ever passed with current master? If `NO_GETCWD` is defined, there's no definition for `LFS_MAXPATHLEN`, which I would expect to result in an `error: ‘LFS_MAXPATHLEN’ undeclared (first use in this function)`.

**Comment by n1tehawk** [comment]
I reworked my previous version. The  `getcwd_error` string constant gets used only once, which makes a macro definition somewhat pointless. I also disliked the fact that `#ifdef NO_GETCWD` now was handled in multiple source locations. I've removed the first one (and the corresponding macros used for *NO_GETCWD*), and relocated the `LFS_MAXPATHLEN` definition to the existing `#ifdef _WIN32` block.

These commits should **preferably be squashed** before merging them. If you want me to, I can update (force-push) this PR accordingly.

Regards, NiteHawk

**Pull request merged**
